### ISSUE TITLE
Can't Watch Custom Channel

### ISSUE THREAD

**Issue by barkatwhat** [knifftech/FullStream#1]
If you already know what channel you want to watch, it is currently very hard to actually get that channel to be in FullStream

**Comment by knifftech** [comment]
So, what you're saying is that if you're not following the desired channel.
Changing the name in the URL is too hard of a step and i should add a input field or similar somewhere instead?

**Comment by barkatwhat** [comment]
My apologies, I'm running the page in fullscreen mode so I can't see the URL. You know, that is the intended use of the website and the URL syntax isn't explained in your tutorial page.

PS: [Here's a pretty nice list of some things to keep in mind re: UX](http://www.thoughtworks.com/insights/blog/22-rules-ux)

**Comment by knifftech** [comment]
Thank you, i'll see what i can improve on both subjects.

**Comment by knifftech** [comment]
Added a manual input via a search icon in the top bar, can also be accessed by pressing F if not in chat.
