### ISSUE TITLE
Vertical layout

### ISSUE THREAD

**Issue by hvdklauw** [knifftech/FullStream#2]
I was going to build something myself, but it might be easier to build it into this;

I often have multiple things going on at the same time and I put the browser window on half screen (widescreen monitor). In that setup it makes sense to have the top half be video and the bottom half be chat.

Would it be possible to add a sidebar option for "bottom" ??

**Comment by knifftech** [comment]
I never thought about that, sounds like a great idea.
I'll look into it when i have the time, thank you.

**Comment by knifftech** [comment]
Added responsive design where the video and sidebar are on top of each other when the windows is 1000 pixels or less in width.

**Comment by hvdklauw** [comment]
Awesome, thanks
