### ISSUE TITLE
Wont load my stream

### ISSUE THREAD

**Issue by silverskater12Ineedhelp** [knifftech/FullStream#3]
I try to watch streams on fullstream but it says its loading and just stops at where it says twitch and never plays PLS HALP!

**Comment by knifftech** [comment]
Hi, can you provide a screenshot?

**Comment by knifftech** [comment]
I just did a patch, hopefully that fixed it.
If not, let me know.

**Comment by silverskater12Ineedhelp** [comment]
it didn't workthx for trying

**Comment by knifftech** [comment]
Can you explain more about what the issue is?
Maybe provide a screenshot?

**Comment by knifftech** [comment]
No reply in over a week, closing the issue.
