### ISSUE TITLE
No Fullscreen avaliable

### ISSUE THREAD

**Issue by GanilGanilder** [knifftech/FullStream#4]
FullStream updated with the new icons for volume, play/pause, and quality, but, the FULLSCREEN button is gone. Please fix it :sob:

**Comment by knifftech** [comment]
That's Twitch's new HTML5 player and it seems that the fullscreen icon in it is gone when embeded.
Sadly this seems to be out of my control, sorry.

**Comment by knifftech** [comment]
A temporary fix might be to press F11 and use FullStream in fullscreen mode instead.

**Comment by GanilGanilder** [comment]
I see, thanks for the quick tip! ;D
