### ISSUE TITLE
Not Switching After Certain Streams

### ISSUE THREAD

**Issue by AlanDayan** [knifftech/FullStream#7]
While watching it switches to the stream (GiantWaffle) then after the stream goes offline it doesnt switch. Im not sure if you cna fix it but it will help a lot.

**Comment by knifftech** [comment]
If you're referring to the Automatic Switcher there are a few points of note.

- Firstly the switcher needs to be turned on, you can do this in the settings.
To access the settings click the cogs in the top right corner.

- Secondly there needs to be at least one live channel in the list of desired channels for it to switch.

- And thirdly the Twitch API needs to update which might take up to a few minutes as FullStream only checks it every 60 seconds.

Hope this helped and thanks for your feedback.

**Comment by AlanDayan** [comment]
The switcher is turned on as is automatically switched to the stream. Multiple other streams were online. And lastly the stream just doesnt update after the stream goes offline it will stay on the offline screen until I refresh the page.

**Comment by knifftech** [comment]
Should be resolved now.
